// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egjkqiwqjfjefyyaecoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnamtxaXdxamZqZWZ5eWFlY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjkxMzMsImV4cCI6MjA2MjU0NTEzM30.7UeGbY-t4Hx4XXfAZGQOcyNpwrJnuG2kF5Hvxb1XPrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);