// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuvvkniozmvwffqbxwir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dnZrbmlvem12d2ZmcWJ4d2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjA0MDcsImV4cCI6MjA2MzEzNjQwN30.M8jO46Fov37QOm-V8ZJ0ERAHmkNVU7nXBtPCPXkK_Qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);